apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fuzzing.fullname" . }}
  labels:
    {{- include "fuzzing.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Fuzzing App</title>
    </head>
    <body>
        <h1>Hello World</h1>
    </body>
    </html>
